name: Build x86_64 Dockermox

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: wget -O Dockerfile "https://raw.githubusercontent.com/rtedpro-cpu/dockermox/refs/heads/main/.github/workflows/Dockerfile" && docker build . --file Dockerfile --tag rtedpro/dockermox:$(date +%s)
